version: '3.3'

services:
    web:
        # command: >
        #     sh -c "
        #         tail -f /dev/null
        #         "

        build:
            context: .
        # restart: always
        volumes:
            - static-data:/vol/web
        environment:
            - SECRET_KEY=devesecretkey
            - DB_HOST=db
            - DB_USER=devuser
            - DB_PASS=changeme
            - ALLOWED_HOSTS=78.46.176.143,treadlog.com

        depends_on:
            - db

    db:
        image: postgres:13-alpine
        # restart: always
        volumes:
            - test-postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changeme
            - PGDATA=/var/lib/postgresql/data/
    proxy:
        # command: >
        #     sh -c "
        #         tail -f /dev/null
        #         "

        build:
            context: ./proxy
        # restart: always
        depends_on:
            - web
        ports:
            - 80:8000
        volumes:
            - static-data:/vol/static

volumes:
    test-postgres-data:
    static-data:
