version: '3.3'

services:
    app:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./app:/app
        environment:
            - SECRET_KEY=devesecretkey
            - DEBUG=1
            - DB_HOST=db
            - DB_USER=devuser
            - DB_PASS=changeme
        depends_on:
            - db
    db:
        image: postgres:13-apline
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changeme

